services:
    LSB\ShippingBundle\Repository\MethodRepository:
        arguments:
            - '@doctrine'
    LSB\ShippingBundle\Repository\MethodRepositoryInterface: '@LSB\ShippingBundle\Repository\MethodRepository'